const Q=[
['Paleoindians','Indigenous America','Which term describes the earliest known inhabitants of the Americas, often associated with Ice Age migration and large-game hunting?','Paleoindians lived during the earliest widely recognized period of human settlement in the Americas.'],
['Archaic People','Indigenous America','Which people adapted to warmer post-Ice Age climates by using broader food sources and more regional lifestyles?','Archaic communities hunted smaller animals, gathered many foods, and developed regionally distinct ways of life.'],
['Hohokam/Anasazi','Indigenous America','Which paired term connects sophisticated desert irrigation canals with pueblos and cliff dwellings in the Southwest?','The Hohokam are known for irrigation systems; Ancestral Puebloans were known for pueblos and cliff dwellings.'],
['Cahokia','Bold-Term Boss','Which large Mississippian city near present-day St. Louis featured huge earthen mounds and wide trade networks?','Cahokia demonstrates the scale and complexity of pre-Columbian urban society in North America.',1],
['The Taíno','Indigenous America','Which Caribbean Indigenous people encountered Columbus and suffered catastrophic losses from disease, violence, and forced labor?','The Taíno lived across parts of the Caribbean at the time of Spanish arrival.'],
['The Aztecs','Indigenous America','Which tribute empire was centered at Tenochtitlan before its defeat by Cortés, Indigenous allies, and disease?','The Aztec Empire controlled a broad tribute network from its capital, Tenochtitlan.'],
['Cabeza de Vaca','Spanish Exploration','Which Spanish shipwreck survivor traveled through the Gulf Coast and Southwest and later wrote about the Indigenous peoples he encountered?','Cabeza de Vaca’s account became an important description of the region and encouraged later exploration.'],
['Pueblo Revolt','Resistance','Which 1680 uprising drove Spanish colonists out of New Mexico for about twelve years?','The Pueblo Revolt was one of the most successful Indigenous rebellions against European colonial rule.'],
['Indentured Servitude','Labor Systems','Which labor system exchanged several years of work for passage, food, and shelter?','Indentured servitude was temporary contract labor, especially important in the early Chesapeake.'],
['Bacon’s Rebellion','Colonial Conflict','Which 1676 Virginia uprising exposed class tensions, frontier conflict, and anger toward Governor William Berkeley?','Bacon’s Rebellion involved land, Native policy, political exclusion, and resentment among poorer colonists.'],
['Anne Hutchinson','Bold-Term Boss','Which Puritan dissenter challenged Massachusetts religious authorities and was banished?','Anne Hutchinson challenged both Puritan leadership and expectations placed on women.',1],
['Pequot War','Native–Colonial Wars','Which 1636–1638 conflict included the English-led attack at Mystic and devastated Pequot political power?','The Pequot War strengthened English expansion in southern New England.'],
['Beaver Wars','Bold-Term Boss','Which conflicts involved the Iroquois Confederacy, neighboring Native peoples, the fur trade, and European firearms?','The Beaver Wars grew from competition over trade, territory, alliances, and access to European goods.',1],
['Praying Towns','Religion','What were Puritan-supervised communities created for Native converts to Christianity?','Praying Towns combined missionary conversion with pressure toward English cultural practices.'],
['King Philip’s War','Native–Colonial Wars','Which devastating 1675–1676 New England conflict was led by Native forces associated with Metacom?','English colonists called Metacom “King Philip.” The war severely weakened Native power in southern New England.'],
['Columbian Exchange','Atlantic World','What term describes the movement of plants, animals, diseases, people, and ideas between the Eastern and Western Hemispheres?','The Columbian Exchange transformed diets, environments, economies, and populations across the Atlantic world.'],
['New Amsterdam','Colonial Settlements','Which Dutch settlement on Manhattan became New York after England seized it in 1664?','New Amsterdam was a diverse commercial center in the Dutch colony of New Netherland.'],
['William Penn','Colonial Settlements','Which Quaker founded Pennsylvania and promoted religious toleration?','William Penn established Pennsylvania as a proprietary colony associated with Quaker ideals.'],
['Olaudah Equiano','Slavery and Abolition','Which formerly enslaved writer described enslavement and the Middle Passage in a famous autobiography?','Olaudah Equiano became an influential voice in the British abolitionist movement.'],
['Stono Rebellion','Slavery and Resistance','Which 1739 South Carolina slave uprising moved toward Spanish Florida in search of freedom?','The Stono Rebellion led South Carolina to impose harsher restrictions through the Negro Act of 1740.'],
['Task System/Gang System','Bold-Term Boss','Which paired term contrasts assigned daily work with continuous group labor under close supervision?','The task system assigned a set amount of work; the gang system organized continuous supervised labor.',1],
['San Diego de Alcalá','Spanish Colonization','Which mission, founded in 1769, was the first Spanish mission established in California?','San Diego de Alcalá represented Spain’s effort to claim California and extend missionary control.'],
['French and Indian War','Imperial Wars','Which 1754–1763 conflict ended with Britain defeating France in North America and taking on heavy war debt?','The French and Indian War was the North American theater of the global Seven Years’ War.'],
['Pontiac’s Rebellion','Resistance','Which 1763 Indigenous uprising challenged British policies in the Great Lakes and Ohio Valley?','Pontiac’s Rebellion followed Britain’s victory over France and reflected anger at new British policies.'],
['Proclamation of 1763','Road to Revolution','Which British order attempted to restrict colonial settlement west of the Appalachian Mountains?','Britain hoped to reduce costly frontier warfare, but many colonists and land speculators resented the restriction.'],
['Great Awakening','Religion','Which revival movement of the 1730s and 1740s emphasized emotional preaching and personal conversion?','The Great Awakening challenged established religious authority and encouraged denominational growth.'],
['Baptists','Religion','Which Protestant group emphasized believer’s baptism, personal conversion, and religious liberty?','Baptists expanded during and after the Great Awakening.'],
['Comanches','Great Plains','Which equestrian people became a major southern Great Plains power through horses, trade, warfare, and raiding?','Comanche power reshaped politics and exchange across the southern Plains and borderlands.'],
['Boston Massacre','Road to Revolution','Which 1770 confrontation became Patriot propaganda after British soldiers killed five colonists?','The Boston Massacre intensified anti-British feeling and was used powerfully in colonial propaganda.'],
['Boston Tea Party','Road to Revolution','Which 1773 protest involved colonists dumping British tea into Boston Harbor?','Britain answered the Boston Tea Party with the punitive Coercive, or Intolerable, Acts.']
].map(([answer,category,clue,explanation,boss=0])=>({answer,category,clue,explanation,boss:Boolean(boss)}));

const T=[
['pequot',1636,'Pequot War begins — 1636'],['amsterdam',1664,'England seizes New Amsterdam — 1664'],['king',1675,'King Philip’s War begins — 1675'],['bacon',1676,'Bacon’s Rebellion — 1676'],['pueblo',1680,'Pueblo Revolt — 1680'],['stono',1739,'Stono Rebellion — 1739'],['french',1754,'French and Indian War begins — 1754'],['pontiac',1763,'Pontiac’s Rebellion — 1763'],['massacre',1770,'Boston Massacre — 1770'],['tea',1773,'Boston Tea Party — 1773']
].map(([id,year,label])=>({id,year,label}));

const $=s=>document.querySelector(s), els={menu:$('#menu'),game:$('#game'),results:$('#results'),puzzle:$('#puzzle'),score:$('#score'),streak:$('#streak'),count:$('#questionCount'),best:$('#bestScore'),heroLabel:$('#heroLabel'),heroBar:$('#heroBar'),enemyLabel:$('#enemyLabel'),enemyBar:$('#enemyBar'),category:$('#category'),timer:$('#timer'),burst:$('#burst'),progress:$('#progress'),prompt:$('#prompt'),answers:$('#answers'),feedback:$('#feedback'),next:$('#next'),resultTitle:$('#resultTitle'),resultStats:$('#resultStats'),missedWrap:$('#missedWrap'),missed:$('#missed'),timeline:$('#timeline'),puzzleFeedback:$('#puzzleFeedback'),soundBtn:$('#soundBtn')};
const S={list:[],i:0,score:0,streak:0,shields:3,missed:[],locked:false,burst:false,timerId:null,seconds:null,puzzle:[],sound:true};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function show(name){['menu','game','results','puzzle'].forEach(x=>els[x].classList.toggle('hidden',x!==name));scrollTo({top:0,behavior:'smooth'})}
function best(){return Number(localStorage.getItem('berryHistoryBest')||0)}
function saveBest(){if(S.score>best())localStorage.setItem('berryHistoryBest',S.score);els.best.textContent=best()}
function resetDash(){els.score.textContent=0;els.streak.textContent='0 🔥';els.count.textContent='0/0';els.best.textContent=best()}
function update(){els.score.textContent=S.score;els.streak.textContent=`${S.streak} 🔥`;els.count.textContent=S.list.length?`${Math.min(S.i+1,S.list.length)}/${S.list.length}`:'0/0';els.heroLabel.textContent=`${S.shields} shield${S.shields===1?'':'s'}`;els.heroBar.style.width=`${S.shields/3*100}%`;const left=Math.max(0,S.list.length-S.i);els.enemyLabel.textContent=`${left} question${left===1?'':'s'} left`;els.enemyBar.style.width=`${S.list.length?left/S.list.length*100:0}%`;els.progress.style.width=`${S.list.length?S.i/S.list.length*100:0}%`;els.burst.disabled=!S.burst||S.locked}
function start(mode){clearInterval(S.timerId);const all=shuffle(Q);S.list=mode==='warmup'?all.slice(0,10):mode==='exam'?all.slice(0,25):mode==='boss'?shuffle(Q.filter(q=>q.boss)):all;Object.assign(S,{i:0,score:0,streak:0,shields:3,missed:[],locked:false,burst:false,seconds:mode==='exam'?1800:null});if(S.seconds!==null){els.timer.classList.remove('hidden');tick();S.timerId=setInterval(()=>{S.seconds--;tick();if(S.seconds<=0)end(true)},1000)}else els.timer.classList.add('hidden');show('game');render()}
function tick(){const m=String(Math.floor(S.seconds/60)).padStart(2,'0'),s=String(S.seconds%60).padStart(2,'0');els.timer.textContent=`${m}:${s}`}
function options(q){return shuffle([q.answer,...shuffle(Q.filter(x=>x.answer!==q.answer).map(x=>x.answer)).slice(0,3)])}
function render(){S.locked=false;els.feedback.classList.add('hidden');els.next.classList.add('hidden');const q=S.list[S.i];els.category.textContent=q.boss?`👑 ${q.category}`:q.category;els.prompt.textContent=q.clue;els.answers.replaceChildren();options(q).forEach(text=>{const b=document.createElement('button');b.type='button';b.className='answer';b.textContent=text;b.dataset.answer=text;b.addEventListener('click',()=>choose(b,q));els.answers.append(b)});update()}
function choose(btn,q){if(S.locked)return;S.locked=true;const correct=btn.dataset.answer===q.answer;[...els.answers.children].forEach(b=>{b.disabled=true;if(b.dataset.answer===q.answer)b.classList.add('correct')});if(correct){S.streak++;S.score+=100+Math.max(0,S.streak-1)*15;if(S.streak%3===0)S.burst=true;els.feedback.innerHTML=`<strong>🍓 Critical hit!</strong><div>${q.explanation}</div>`;tone(660,.09)}else{btn.classList.add('wrong');S.streak=0;S.shields=Math.max(0,S.shields-1);if(!S.missed.includes(q.answer))S.missed.push(q.answer);els.feedback.innerHTML=`<strong>📚 Study shield used!</strong><div>The answer is <strong>${q.answer}</strong>. ${q.explanation}</div>`;tone(220,.12)}els.feedback.classList.remove('hidden');els.next.classList.remove('hidden');update()}
function next(){S.i++;S.i>=S.list.length?end(false):render()}
function burst(){if(!S.burst||S.locked)return;const q=S.list[S.i];shuffle([...els.answers.children].filter(b=>b.dataset.answer!==q.answer&&!b.disabled)).slice(0,2).forEach(b=>{b.disabled=true;b.classList.add('faded')});S.burst=false;els.feedback.innerHTML='<strong>✨ Berry Burst!</strong><div>Two incorrect answers disappeared.</div>';els.feedback.classList.remove('hidden');update();tone(880,.08)}
function end(timedOut){clearInterval(S.timerId);const answered=timedOut?S.i:S.list.length,correct=Math.max(0,answered-S.missed.length),accuracy=answered?Math.round(correct/answered*100):0;els.resultTitle.textContent=timedOut?'⏰ Time expired—but your study data survived!':accuracy>=88?'👑 Berry Scholar Victory!':accuracy>=70?'🍓 Strong Battle!':'🌱 Training Arc Unlocked!';els.resultStats.textContent=`${S.score} points • ${accuracy}% accuracy • ${S.missed.length} term${S.missed.length===1?'':'s'} to review`;els.missed.replaceChildren();els.missedWrap.classList.toggle('hidden',!S.missed.length);S.missed.forEach(x=>{const c=document.createElement('span');c.className='chip';c.textContent=x;els.missed.append(c)});saveBest();show('results')}
function openPuzzle(){clearInterval(S.timerId);S.puzzle=shuffle(T);renderPuzzle();els.puzzleFeedback.textContent='Arrange all ten tiles, then check your timeline.';show('puzzle')}
function renderPuzzle(){els.timeline.replaceChildren();S.puzzle.forEach((ev,i)=>{const li=document.createElement('li');li.className='tile';li.draggable=true;li.dataset.id=ev.id;li.innerHTML=`<span class="num">${i+1}</span><strong>${ev.label}</strong><span class="movers"><button type="button" aria-label="Move up">↑</button><button type="button" aria-label="Move down">↓</button></span>`;const [up,down]=li.querySelectorAll('button');up.addEventListener('click',()=>move(i,-1));down.addEventListener('click',()=>move(i,1));li.addEventListener('dragstart',()=>li.classList.add('dragging'));li.addEventListener('dragend',()=>li.classList.remove('dragging'));li.addEventListener('dragover',e=>e.preventDefault());li.addEventListener('drop',e=>{e.preventDefault();const d=els.timeline.querySelector('.dragging');if(!d||d===li)return;const from=S.puzzle.findIndex(x=>x.id===d.dataset.id),to=S.puzzle.findIndex(x=>x.id===li.dataset.id),[m]=S.puzzle.splice(from,1);S.puzzle.splice(to,0,m);renderPuzzle()});els.timeline.append(li)})}
function move(i,d){const n=i+d;if(n<0||n>=S.puzzle.length)return;[S.puzzle[i],S.puzzle[n]]=[S.puzzle[n],S.puzzle[i]];renderPuzzle()}
function checkPuzzle(){const correct=[...T].sort((a,b)=>a.year-b.year),count=S.puzzle.reduce((n,x,i)=>n+(x.id===correct[i].id),0);els.puzzleFeedback.innerHTML=count===T.length?'<strong>🧁 Quilt complete!</strong><div>Every event is in order. The History Gremlin has been folded.</div>':`<strong>🍓 ${count} of ${T.length} tiles are correct.</strong><div>Use the years to adjust the rest.</div>`;tone(count===T.length?740:300,.1)}
function hint(){const correct=[...T].sort((a,b)=>a.year-b.year),wrong=S.puzzle.findIndex((x,i)=>x.id!==correct[i].id);if(wrong<0)return checkPuzzle();const at=S.puzzle.findIndex(x=>x.id===correct[wrong].id),[m]=S.puzzle.splice(at,1);S.puzzle.splice(wrong,0,m);renderPuzzle();els.puzzleFeedback.textContent=`💡 Hint placed tile ${wrong+1} correctly.`}
function tone(freq,dur){if(!S.sound)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.value=.035;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+dur)}catch{}}

document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.mode)));$('#next').addEventListener('click',next);$('#burst').addEventListener('click',burst);$('#openPuzzle').addEventListener('click',openPuzzle);$('#resultPuzzle').addEventListener('click',openPuzzle);$('#again').addEventListener('click',()=>{resetDash();show('menu')});$('#closePuzzle').addEventListener('click',()=>{resetDash();show('menu')});$('#shufflePuzzle').addEventListener('click',()=>{S.puzzle=shuffle(T);renderPuzzle();els.puzzleFeedback.textContent='🔀 Timeline shuffled. Rebuild it from earliest to latest.'});$('#hintPuzzle').addEventListener('click',hint);$('#checkPuzzle').addEventListener('click',checkPuzzle);els.soundBtn.addEventListener('click',()=>{S.sound=!S.sound;els.soundBtn.setAttribute('aria-pressed',S.sound);els.soundBtn.textContent=S.sound?'🔊 Sound On':'🔇 Sound Off'});resetDash();
